batches: 10
bilayer_eq: false
box:
- 30
- 30
- 300.0
box_eq: false
boxscaling_xyz:
- true
- true
- true
custom_restraint_type: harmonic
custom_restraints: false
cutoff_lj: 2.0
cutoff_yu: 4.0
eps_lj: 0.2
ext_force: false
ext_force_expr: step(d2-18)*d2; d2=periodicdistance(x, y, z, 0, 0, z)^2
fcustom_restraints: custom_restraints.txt
fixed_lambda: 0
frestart: restart.chk
friction: 0.01
friction_coeff: 0.01
gpu_id: 0
ionic: 0.15
k_eq: 0.02
kappa: 0
logfreq: 10000
minimize_energy: true
pH: 7
placement: default
platform: CUDA
pressure:
- 0
- 0
- 0
pressure_coupling: false
random_number_seed: null
report_potential_energy: true
restart: checkpoint
rsc: 0
rt: 0.75
rt_mode: rt2
runtime: 0
sc_mode: rt2
slab_eq: true
slab_outer: 40
slab_width: 40
softcore: true
steps: 10000
steps_eq: 5000
sysname: NUP98_rt0.75sig_270.15K
temp: 270.15
threads: 1
topol: slab
total_steps: 100000
verbose: true
wfreq: 10000
